zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - "2181:2181"
    - "22"
kafka:
  image: jeado/kafka:0.9.0.0
  ports:
    - "9092:9092"
  links:
    - zookeeper:zk
  environment:
    - KAFKA_ADVERTISED_HOST_NAME=${KAFKA_ADVERTISED_HOST_NAME}
    - KAFKA_CREATE_TOPICS=device-data:3:1
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
